=== SuperYoshi10000/SkillsMod/src/main/resources/player_skills.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Player Skills",
  "description": "Player skills are used to modify the player's attributes and abilities.",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "base": { "type": "number" },
    "max_level": { "type": "number" },
    "levels": {
      "oneOf": [{
        "type": "object",
        "properties": {
          "xp": { "type": "number" },
          "modifiers": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "attribute": { "type": "string" },
                "id": { "type": "string" },
                "operation": { "enum": ["add_value", "add_multiplied_base", "add_multiplied_total"] },
                "value": { "type": "number" }
              },
              "required": ["attribute", "id", "operation", "value"]
            }
          }
        }
      }, {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "xp": { "type": "number" },
            "modifiers": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "attribute": { "type": "string" },
                  "id": { "type": "string" },
                  "operation": { "enum": ["add_value", "add_multiplied_base", "add_multiplied_total"] },
                  "value": { "type": "number" }
                },
                "required": ["attribute", "id", "operation", "value"]
              }
            }
          }
        }
      }]
    },
    "stack_lower_levels": { "type": "boolean" },
    "xp_required": { "type": "array", "items": { "type": "number" } },
    "enabled": { "type": "boolean" }
  },
  "required": ["id", "base", "max_level", "levels"]
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/player_skills/jump_strength.json
{
  "base": 0.41999998688697815,
  "id": "skills:jump_strength",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:jump_strength",
        "id": "skills:upgrade/jump_strength",
        "operation": "add_multiplied_base",
        "value": 0.005
      }
    ],
    "xp": 10
  },
  "max_level": 100
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/tempt_range.json
{
  "base": 10.0,
  "id": "skills:tempt_range",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:tempt_range",
        "id": "skills:upgrade/tempt_range",
        "operation": "add_multiplied_base",
        "value": 0.02
      }
    ],
    "xp": 20
  },
  "max_level": 100,
  "enabled": false
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/player_skills/gravity.json
{
  "base": 0.08,
  "id": "skills:gravity",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:gravity",
        "id": "skills:upgrade/gravity",
        "operation": "add_multiplied_base",
        "value": 0.02
      }
    ],
    "xp": 20
  },
  "max_level": 100,
  "enabled": false
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/player_skills/follow_range.json
{
  "base": 32.0,
  "id": "skills:follow_range",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:follow_range",
        "id": "skills:upgrade/follow_range",
        "operation": "add_multiplied_base",
        "value": 0.02
      }
    ],
    "xp": 20
  },
  "max_level": 100,
  "enabled": false
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/player_skills/attack_speed.json
{
  "base": 4.0,
  "id": "skills:attack_speed",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:attack_speed",
        "id": "skills:upgrade/attack_speed",
        "operation": "add_multiplied_base",
        "value": 0.01
      }
    ],
    "xp": 20
  },
  "max_level": 100
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/player_skills/sweeping_damage_ratio.json
{
  "base": 0.0,
  "id": "skills:sweeping_damage_ratio",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:sweeping_damage_ratio",
        "id": "skills:upgrade/sweeping_damage_ratio",
        "operation": "add_value",
        "value": 0.01
      }
    ],
    "xp": 20
  },
  "max_level": 100
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/player_skills/movement_efficiency.json
{
  "base": 0.0,
  "id": "skills:movement_efficiency",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:movement_efficiency",
        "id": "skills:upgrade/movement_efficiency",
        "operation": "add_value",
        "value": 0.01
      }
    ],
    "xp": 20
  },
  "max_level": 100
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/player_skills/fall_damage_multiplier.json
{
  "base": 1.0,
  "id": "skills:fall_damage_multiplier",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:fall_damage_multiplier",
        "id": "skills:upgrade/fall_damage_multiplier",
        "operation": "add_value",
        "value": -0.008
      }
    ],
    "xp": 20
  },
  "max_level": 100
}
