=== SuperYoshi10000/SkillsMod/src/main/resources/player_skills.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Player Skills",
  "description": "Player skills are used to modify the player's attributes and abilities.",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "base": { "type": "number" },
    "max_level": { "type": "number" },
    "levels": {
      "oneOf": [{
        "type": "object",
        "properties": {
          "xp": { "type": "number" },
          "modifiers": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "attribute": { "type": "string" },
                "id": { "type": "string" },
                "operation": { "enum": ["add_value", "add_multiplied_base", "add_multiplied_total"] },
                "value": { "type": "number" }
              },
              "required": ["attribute", "id", "operation", "value"]
            }
          }
        }
      }, {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "xp": { "type": "number" },
            "modifiers": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "attribute": { "type": "string" },
                  "id": { "type": "string" },
                  "operation": { "enum": ["add_value", "add_multiplied_base", "add_multiplied_total"] },
                  "value": { "type": "number" }
                },
                "required": ["attribute", "id", "operation", "value"]
              }
            }
          }
        }
      }]
    },
    "stack_lower_levels": { "type": "boolean" },
    "xp_required": { "type": "array", "items": { "type": "number" } },
    "enabled": { "type": "boolean" }
  },
  "required": ["id", "base", "max_level", "levels"]
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/armor_toughness.json
{
  "base": 0.0,
  "id": "skills:armor_toughness",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:armor_toughness",
        "id": "skills:upgrade/armor_toughness",
        "operation": "add_value",
        "value": 0.01
      }
    ],
    "xp": 20
  },
  "max_level": 100,
  "enabled": false
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/player_skills/spawn_reinforcements.json
{
  "base": 0.0,
  "id": "skills:spawn_reinforcements",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:spawn_reinforcements",
        "id": "skills:upgrade/spawn_reinforcements",
        "operation": "add_multiplied_base",
        "value": 0.02
      }
    ],
    "xp": 20
  },
  "max_level": 100,
  "enabled": false
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/player_skills/mining_efficiency.json
{
  "base": 0.0,
  "id": "skills:mining_efficiency",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:mining_efficiency",
        "id": "skills:upgrade/mining_efficiency",
        "operation": "add_multiplied_base",
        "value": 0.02
      }
    ],
    "xp": 20
  },
  "max_level": 100,
  "enabled": false
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/player_skills/flying_speed.json
{
  "base": 0.4,
  "id": "skills:flying_speed",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:flying_speed",
        "id": "skills:upgrade/flying_speed",
        "operation": "add_multiplied_base",
        "value": 0.02
      }
    ],
    "xp": 20
  },
  "max_level": 100,
  "enabled": false
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/player_skills/water_movement_efficiency.json
{
  "base": 0.0,
  "id": "skills:water_movement_efficiency",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:water_movement_efficiency",
        "id": "skills:upgrade/water_movement_efficiency",
        "operation": "add_value",
        "value": 0.005
      }
    ],
    "xp": 20
  },
  "max_level": 100
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/player_skills/safe_fall_distance.json
{
  "base": 3.0,
  "id": "skills:safe_fall_distance",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:safe_fall_distance",
        "id": "skills:upgrade/safe_fall_distance",
        "operation": "add_value",
        "value": 0.05
      }
    ],
    "xp": 20
  },
  "max_level": 100
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/player_skills/submerged_mining_speed.json
{
  "base": 0.2,
  "id": "skills:submerged_mining_speed",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:submerged_mining_speed",
        "id": "skills:upgrade/submerged_mining_speed",
        "operation": "add_multiplied_base",
        "value": 0.04
      }
    ],
    "xp": 20
  },
  "max_level": 100
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/block_break_speed.json
{
  "base": 1.0,
  "id": "skills:block_break_speed",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:block_break_speed",
        "id": "skills:upgrade/block_break_speed",
        "operation": "add_multiplied_base",
        "value": 0.02
      }
    ],
    "xp": 20
  },
  "max_level": 100
}
