=== SuperYoshi10000/SkillsMod/src/main/resources/skills.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Player Skills",
  "description": "Player skills are used to modify the player's attributes and abilities.",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "base": { "type": ["number", "null"] },
    "max_level": { "type": "number" },
    "levels": {
      "oneOf": [{
        "$ref": "#/definitions/level"
      }, {
        "type": "array",
        "items": { "$ref": "#/definitions/level" }
      }]
    },
    "stack_lower_levels": { "type": "boolean" },
    "xp_required": { "type": "array", "items": { "type": "number" } },
    "bonus_modifiers": {
      "type": "array",
      "items": { "$ref": "#/definitions/modifier" }
    },
    "bonus_effects": {
      "type": "array",
      "items": { "$ref": "#/definitions/effect" }
    },
    "icon": { "type": "string", "pattern": "([a-z0-9._-]*:)?[a-z0-9/._-]*" },
    "enabled": { "type": "boolean" }
  },
  "required": ["id", "base", "max_level", "levels"],
  "definitions": {
    "level": {
      "type": "object",
      "properties": {
        "xp": { "type": "integer" },
        "modifiers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/modifier"
          }
        },
        "effects": {
          "type": "array",
          "items": { "$ref": "#/definitions/effect" }
        }
      }
    },
    "modifier": {
      "type": "object",
      "properties": {
        "attribute": { "type": "string" },
        "id": { "type": "string" },
        "operation": { "enum": ["add_value", "add_multiplied_base", "add_multiplied_total"] },
        "value": { "type": "number" }
      },
      "required": ["attribute", "id", "operation", "value"]
    },
    "effect": {
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "duration": { "type": "number" },
        "amplifier": { "type": "integer", "minimum": 0, "maximum": 255 },
        "ambient": { "type": "boolean" },
        "show_particles": { "type": "boolean" },
        "show_icon": { "type": "boolean" },
        "hidden_effect": { "$ref": "#/definitions/effect" }
      }
    }
  }
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/entity_interaction_range.json
{
  "base": 3.0,
  "id": "skills:entity_interaction_range",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:entity_interaction_range",
        "id": "skills:upgrade/entity_interaction_range",
        "operation": "add_value",
        "value": 0.1
      }
    ],
    "xp": 25
  },
  "icon": "skills:skill/entity_interaction",
  "max_level": 45
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/water_movement_efficiency.json
{
  "base": 0.0,
  "id": "skills:water_movement_efficiency",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:water_movement_efficiency",
        "id": "skills:upgrade/water_movement_efficiency",
        "operation": "add_value",
        "value": 0.005
      }
    ],
    "xp": 20
  },
  "icon": "minecraft:mob_effect/dolphins_grace",
  "max_level": 100
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/max_absorption.json
{
  "base": 0.0,
  "id": "skills:max_absorption",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:max_absorption",
        "id": "skills:upgrade/max_absorption",
        "operation": "add_value",
        "value": 1
      }
    ],
    "xp": 20
  },
  "icon": "minecraft:mob_effect/absorption",
  "max_level": 20,
  "enabled": false
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/safe_fall_distance.json
{
  "base": 3.0,
  "id": "skills:safe_fall_distance",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:safe_fall_distance",
        "id": "skills:upgrade/safe_fall_distance",
        "operation": "add_value",
        "value": 0.1
      }
    ],
    "xp": 40
  },
  "icon": "minecraft:mob_effect/levitation",
  "max_level": 50
}
