=== SuperYoshi10000/SkillsMod/src/main/resources/skills.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Player Skills",
  "description": "Player skills are used to modify the player's attributes and abilities.",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "base": { "type": ["number", "null"] },
    "max_level": { "type": "number" },
    "levels": {
      "oneOf": [{
        "$ref": "#/definitions/level"
      }, {
        "type": "array",
        "items": { "$ref": "#/definitions/level" }
      }]
    },
    "stack_lower_levels": { "type": "boolean" },
    "xp_required": { "type": "array", "items": { "type": "number" } },
    "bonus_modifiers": {
      "type": "array",
      "items": { "$ref": "#/definitions/modifier" }
    },
    "bonus_effects": {
      "type": "array",
      "items": { "$ref": "#/definitions/effect" }
    },
    "icon": { "type": "string", "pattern": "([a-z0-9._-]*:)?[a-z0-9/._-]*" },
    "enabled": { "type": "boolean" }
  },
  "required": ["id", "base", "max_level", "levels"],
  "definitions": {
    "level": {
      "type": "object",
      "properties": {
        "xp": { "type": "integer" },
        "modifiers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/modifier"
          }
        },
        "effects": {
          "type": "array",
          "items": { "$ref": "#/definitions/effect" }
        }
      }
    },
    "modifier": {
      "type": "object",
      "properties": {
        "attribute": { "type": "string" },
        "id": { "type": "string" },
        "operation": { "enum": ["add_value", "add_multiplied_base", "add_multiplied_total"] },
        "value": { "type": "number" }
      },
      "required": ["attribute", "id", "operation", "value"]
    },
    "effect": {
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "duration": { "type": "number" },
        "amplifier": { "type": "integer", "minimum": 0, "maximum": 255 },
        "ambient": { "type": "boolean" },
        "show_particles": { "type": "boolean" },
        "show_icon": { "type": "boolean" },
        "hidden_effect": { "$ref": "#/definitions/effect" }
      }
    }
  }
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/attack_knockback.json
{
  "base": 0.0,
  "id": "skills:attack_knockback",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:attack_knockback",
        "id": "skills:upgrade/attack_knockback",
        "operation": "add_value",
        "value": 0.1
      }
    ],
    "xp": 25
  },
  "icon": "skills:skill/attack_knockback",
  "max_level": 50
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/attack_speed.json
{
  "base": 4.0,
  "id": "skills:attack_speed",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:attack_speed",
        "id": "skills:upgrade/attack_speed",
        "operation": "add_multiplied_base",
        "value": 0.1
      }
    ],
    "xp": 40
  },
  "icon": "skills:skill/attack_speed",
  "max_level": 40
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/max_health.json
{
  "base": 20.0,
  "id": "skills:max_health",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:max_health",
        "id": "skills:upgrade/max_health",
        "operation": "add_value",
        "value": 1.0
      }
    ],
    "xp": 25
  },
  "icon": "minecraft:mob_effect/health_boost",
  "max_level": 40
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/sneaking_speed.json
{
  "base": 0.3,
  "id": "skills:sneaking_speed",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:sneaking_speed",
        "id": "skills:upgrade/sneaking_speed",
        "operation": "add_value",
        "value": 0.007
      }
    ],
    "xp": 20
  },
  "icon": "skills:skill/sneaking_speed",
  "max_level": 100
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/jump_strength.json
{
  "base": 0.41999998688697815,
  "id": "skills:jump_strength",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:jump_strength",
        "id": "skills:upgrade/jump_strength",
        "operation": "add_multiplied_base",
        "value": 0.005
      }
    ],
    "xp": 10
  },
  "icon": "minecraft:mob_effect/jump_boost",
  "max_level": 100
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/movement_efficiency.json
{
  "base": 0.0,
  "id": "skills:movement_efficiency",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:movement_efficiency",
        "id": "skills:upgrade/movement_efficiency",
        "operation": "add_value",
        "value": 0.009
      }
    ],
    "xp": 20
  },
  "icon": "skills:skill/movement_efficiency",
  "max_level": 100
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/luck.json
{
  "base": 0.0,
  "id": "skills:luck",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:luck",
        "id": "skills:upgrade/luck",
        "operation": "add_value",
        "value": 1.0
      }
    ],
    "xp": 20
  },
  "icon": "minecraft:mob_effect/luck",
  "max_level": 100
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/oxygen_bonus.json
{
  "base": 0.0,
  "id": "skills:oxygen_bonus",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:oxygen_bonus",
        "id": "skills:upgrade/oxygen_bonus",
        "operation": "add_value",
        "value": 1
      }
    ],
    "xp": 10
  },
  "icon": "minecraft:mob_effect/water_breathing",
  "max_level": 33
}
