=== SuperYoshi10000/SkillsMod/src/main/resources/skills.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Player Skills",
  "description": "Player skills are used to modify the player's attributes and abilities.",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "base": { "type": ["number", "null"] },
    "max_level": { "type": "number" },
    "levels": {
      "oneOf": [{
        "$ref": "#/definitions/level"
      }, {
        "type": "array",
        "items": { "$ref": "#/definitions/level" }
      }]
    },
    "stack_lower_levels": { "type": "boolean" },
    "xp_required": { "type": "array", "items": { "type": "number" } },
    "bonus_modifiers": {
      "type": "array",
      "items": { "$ref": "#/definitions/modifier" }
    },
    "bonus_effects": {
      "type": "array",
      "items": { "$ref": "#/definitions/effect" }
    },
    "icon": { "type": "string", "pattern": "([a-z0-9._-]*:)?[a-z0-9/._-]*" },
    "enabled": { "type": "boolean" }
  },
  "required": ["id", "base", "max_level", "levels"],
  "definitions": {
    "level": {
      "type": "object",
      "properties": {
        "xp": { "type": "integer" },
        "modifiers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/modifier"
          }
        },
        "effects": {
          "type": "array",
          "items": { "$ref": "#/definitions/effect" }
        }
      }
    },
    "modifier": {
      "type": "object",
      "properties": {
        "attribute": { "type": "string" },
        "id": { "type": "string" },
        "operation": { "enum": ["add_value", "add_multiplied_base", "add_multiplied_total"] },
        "value": { "type": "number" }
      },
      "required": ["attribute", "id", "operation", "value"]
    },
    "effect": {
      "type": "object",
      "properties": {
        "id": { "type": "string" },
        "duration": { "type": "number" },
        "amplifier": { "type": "integer", "minimum": 0, "maximum": 255 },
        "ambient": { "type": "boolean" },
        "show_particles": { "type": "boolean" },
        "show_icon": { "type": "boolean" },
        "hidden_effect": { "$ref": "#/definitions/effect" }
      }
    }
  }
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/submerged_mining_speed.json
{
  "base": 0.2,
  "id": "skills:submerged_mining_speed",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:submerged_mining_speed",
        "id": "skills:upgrade/submerged_mining_speed",
        "operation": "add_multiplied_base",
        "value": 0.04
      }
    ],
    "xp": 40
  },
  "icon": "minecraft:mob_effect/conduit_power",
  "max_level": 25
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/fall_damage_multiplier.json
{
  "base": 1.0,
  "id": "skills:fall_damage_multiplier",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:fall_damage_multiplier",
        "id": "skills:upgrade/fall_damage_multiplier",
        "operation": "add_value",
        "value": -0.01
      }
    ],
    "xp": 20
  },
  "icon": "minecraft:mob_effect/slow_falling",
  "max_level": 80
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/knockback_resistance.json
{
  "base": 0.0,
  "id": "skills:knockback_resistance",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:knockback_resistance",
        "id": "skills:upgrade/knockback_resistance",
        "operation": "add_value",
        "value": 0.02
      }
    ],
    "xp": 50
  },
  "icon": "skills:skill/knockback_resistance",
  "max_level": 50
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/block_interaction_range.json
{
  "base": 4.5,
  "id": "skills:block_interaction_range",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:block_interaction_range",
        "id": "skills:upgrade/block_interaction_range",
        "operation": "add_value",
        "value": 0.1
      }
    ],
    "xp": 25
  },
  "icon": "skills:skill/block_interaction",
  "max_level": 50
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/movement_speed.json
{
  "base": 0.7,
  "id": "skills:movement_speed",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:movement_speed",
        "id": "skills:upgrade/movement_speed",
        "operation": "add_multiplied_base",
        "value": 0.015
      }
    ],
    "xp": 20
  },
  "icon": "minecraft:mob_effect/speed",
  "max_level": 100
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/reduce_burning_time.json
{
  "base": 1.0,
  "id": "skills:reduce_burning_time",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:burning_time",
        "id": "skills:upgrade/reduce_burning_time",
        "operation": "add_value",
        "value": -0.01
      }
    ],
    "xp": 20
  },
  "icon": "minecraft:mob_effect/fire_resistance",
  "max_level": 90
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/step_height.json
{
  "base": 0.6,
  "id": "skills:step_height",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:step_height",
        "id": "skills:upgrade/step_height",
        "operation": "add_value",
        "value": 0.01
      }
    ],
    "xp": 20
  },
  "icon": "skills:skill/step_height",
  "max_level": 100
}

=== SuperYoshi10000/SkillsMod/src/main/generated/data/skills/skill/explosion_knockback_resistance.json
{
  "base": 0.0,
  "id": "skills:explosion_knockback_resistance",
  "levels": {
    "modifiers": [
      {
        "attribute": "minecraft:explosion_knockback_resistance",
        "id": "skills:upgrade/explosion_knockback_resistance",
        "operation": "add_value",
        "value": 0.01
      }
    ],
    "xp": 20
  },
  "icon": "skills:skill/explosion_knockback_resistance",
  "max_level": 50
}
